export const table=[
  {
    "id": 1,
    "title": "Project A",
    "pm": "John Doe",
    "deadline": "2024-10-05",
    "status": "ongoing",
    "crew": ["Alice", "Bob", "Charlie"],
    "client": "Client X",
    "final_file": "file_a.zip",
    "final_report_file": "report_a.pdf",
    "note": "Initial phase complete"
  },
  {
    "id": 2,
    "title": "Project B",
    "pm": "Jane Smith",
    "deadline": "2024-11-15",
    "status": "done",
    "crew": ["David", "Eva", "Frank", "Grace"],
    "client": "Client Y",
    "final_file": "file_b.zip",
    "final_report_file": "report_b.pdf",
    "note": "Completed ahead of schedule"
  },
  {
    "id": 3,
    "title": "Project C",
    "pm": "Emily Clark",
    "deadline": "2024-12-01",
    "status": "ongoing",
    "crew": ["Helen", "Ian", "Jack"],
    "client": "Client Z",
    "final_file": "file_c.zip",
    "final_report_file": "report_c.pdf",
    "note": "Awaiting client feedback"
  },
  {
    "id": 4,
    "title": "Project D",
    "pm": "Michael Brown",
    "deadline": "2024-09-30",
    "status": "cancel",
    "crew": ["Kim", "Leo", "Mia", "Nina", "Oscar"],
    "client": "Client A",
    "final_file": "file_d.zip",
    "final_report_file": "report_d.pdf",
    "note": "Project canceled due to budget cuts"
  },
  {
    "id": 5,
    "title": "Project E",
    "pm": "John Doe",
    "deadline": "2024-10-22",
    "status": "done",
    "crew": ["Paul", "Quincy", "Rachel"],
    "client": "Client B",
    "final_file": "file_e.zip",
    "final_report_file": "report_e.pdf",
    "note": "Successful completion"
  },
  {
    "id": 6,
    "title": "Project F",
    "pm": "Jane Smith",
    "deadline": "2024-08-14",
    "status": "done",
    "crew": ["Steve", "Tina", "Uma", "Victor"],
    "client": "Client C",
    "final_file": "file_f.zip",
    "final_report_file": "report_f.pdf",
    "note": "Completed on time"
  },
  {
    "id": 7,
    "title": "Project G",
    "pm": "Emily Clark",
    "deadline": "2024-12-05",
    "status": "ongoing",
    "crew": ["Wendy", "Xander", "Yvonne"],
    "client": "Client D",
    "final_file": "file_g.zip",
    "final_report_file": "report_g.pdf",
    "note": "Mid-project review scheduled"
  },
  {
    "id": 8,
    "title": "Project H",
    "pm": "Michael Brown",
    "deadline": "2024-07-25",
    "status": "done",
    "crew": ["Zane", "Alice", "Bob"],
    "client": "Client E",
    "final_file": "file_h.zip",
    "final_report_file": "report_h.pdf",
    "note": "Client satisfied with the results"
  },
  {
    "id": 9,
    "title": "Project I",
    "pm": "John Doe",
    "deadline": "2024-09-10",
    "status": "ongoing",
    "crew": ["Charlie", "David", "Eva"],
    "client": "Client F",
    "final_file": "file_i.zip",
    "final_report_file": "report_i.pdf",
    "note": "Final review phase"
  },
  {
    "id": 10,
    "title": "Project J",
    "pm": "Jane Smith",
    "deadline": "2024-11-22",
    "status": "ongoing",
    "crew": ["Frank", "Grace", "Helen", "Ian"],
    "client": "Client G",
    "final_file": "file_j.zip",
    "final_report_file": "report_j.pdf",
    "note": "Project on track"
  }
]
